environment: PRODUCTION
spring:
  application:
    name: exchange-service
  config:
    activate:
      on-profile: prod
eureka:
  client:
    service-url:
      defaultZone: http://${registry.hostname}:${registry.port}/eureka
