environment: DEVELOPMENT
spring:
  application:
    name: exchange-service
  config:
    activate:
      on-profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://${registry.hostname}:${registry.port}/eureka
