environment: INTEGRATION-TEST
spring:
  application:
    name: booking-service
  config:
    activate:
      on-profile: itdb
  datasource:
    url: jdbc:h2:mem:itdb #jdbc:h2:file:./devdb
    driverClassName: org.h2.Driver
    username: sa
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
eureka:
  client:
    service-url:
      defaultZone: http://${registry.hostname}:${registry.port}/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 50000
