environment: PRODUCTION
spring:
  application:
    name: booking-service
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:proddb
    driver-class-name: org.h2.Driver
    username: sa
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
eureka:
  client:
    service-url:
      defaultZone: http://${registry.hostname}:${registry.port}/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 8000
        readTimeout: 10000
