environment: DEVELOPMENT
spring:
  application:
    name: booking-service
  config:
    activate:
      on-profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://${registry.hostname}:${registry.port}/eureka
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 50000
